(() => {
  'use strict';
  const POLL_MS=30000, PREF_KEY='nfl-fantasycast-view-v1';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const list=v=>Array.isArray(v)?v:[];
  const finite=v=>typeof v==='number'&&Number.isFinite(v);
  const points=v=>finite(v)?v.toFixed(2):'—';
  const safeURL=v=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
  const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const dateBound=offset=>{const d=new Date();d.setDate(d.getDate()+offset);return localDate(d);};
  const dateLabel=v=>{const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});};
  const timeLabel=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'Time unavailable':d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});};
  const stamp=v=>{if(!v)return 'No successful check';const d=new Date(v);return Number.isNaN(d.getTime())?'No successful check':d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'});};
  let host=null, options={}, timer=0, dashboardRequest=null, gameRequest=null, dashboardSeq=0, gameSeq=0, refreshSeq=0;
  let s;
  function saved(){try{return JSON.parse(localStorage.getItem(PREF_KEY))||{};}catch{return {};}}
  function persist(){try{localStorage.setItem(PREF_KEY,JSON.stringify({focus:s.focus,density:s.density,auto:s.auto}));}catch{}}
  const leagues=()=>list(options.leagues||window.NFL_GUIDE?.leagues||window.NFL_APP?.data?.leagues);
  const selectedLeague=()=>s?.dashboard?.league||leagues().find(l=>String(l.id)===s.league)||{};
  const games=()=>list(s?.dashboard?.games);
  const game=()=>s?.detail?.id===s.gameId?s.detail.game||games().find(g=>String(g.id)===s.gameId):games().find(g=>String(g.id)===s.gameId);
  function teams(){const m=s?.dashboard?.matchup;return [{key:'own',label:'Your team',data:m?.own},{key:'opponent',label:'Opponent',data:m?.opponent}];}
  function allPlayers(side){const t=teams().find(t=>t.key===side)?.data;return [...list(t?.starters),...list(t?.bench),...list(t?.injuredReserve),...list(t?.taxi)];}
  function selectedPlayer(){const [side,...id]=s.player.split(':');return allPlayers(side).find(p=>String(p.id)===id.join(':'));}
  function playerGame(p){return p?.gameId?games().find(g=>String(g.id)===String(p.gameId)):null;}
  function connected(g,side){return allPlayers(side).filter(p=>p.gameId&&String(p.gameId)===String(g.id));}
  function status(g){return g?.status||(g?.state==='pre'?timeLabel(g.startTime):g?.state==='post'?'Final':'Status unavailable');}
  function link(url,text,cls=''){const u=safeURL(url);return u?`<a class="${cls}" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(text)}<span class="sr-only"> (opens in a new tab)</span></a>`:'';}
  function photo(url,name,cls='gd-avatar'){const u=safeURL(url);return u?`<img class="${cls}" src="${esc(u)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:`<span class="${cls} gd-initials" aria-hidden="true">${esc(String(name||'?').split(' ').map(x=>x[0]).slice(0,2).join(''))}</span>`;}
  function sourceLine(sources){return list(sources).map(x=>`<span class="gd-source gd-source-${esc(['live','cached','stale','snapshot','unavailable'].includes(x.status)?x.status:'unavailable')}"><b>${esc(x.provider||'Source')}</b> ${esc(x.status==='live'?'checked':x.status||'unavailable')} · ${esc(stamp(x.fetchedAt))}${x.error?`<span class="gd-source-error">${esc(x.error)}</span>`:''}${link(x.url,'Source')}</span>`).join('');}
  // Update existing nodes so polling preserves keyboard focus, open disclosures and scroll.
  function morph(current,next){
    if(current.nodeType!==next.nodeType||current.nodeName!==next.nodeName){current.replaceWith(next.cloneNode(true));return;}
    if(current.nodeType===Node.TEXT_NODE){if(current.textContent!==next.textContent)current.textContent=next.textContent;return;}
    if(current.nodeType!==Node.ELEMENT_NODE)return;
    for(const a of [...current.attributes])if(!next.hasAttribute(a.name)&&!(current.tagName==='DETAILS'&&a.name==='open'))current.removeAttribute(a.name);
    for(const a of next.attributes)if(current.getAttribute(a.name)!==a.value)current.setAttribute(a.name,a.value);
    const keyed=new Map([...current.children].filter(x=>x.dataset.key).map(x=>[x.dataset.key,x]));
    [...next.childNodes].forEach((n,i)=>{let old=current.childNodes[i];const key=n.nodeType===1?n.dataset.key:null;if(key&&keyed.has(key)&&keyed.get(key)!==old){current.insertBefore(keyed.get(key),old||null);old=current.childNodes[i];}if(!old)current.append(n.cloneNode(true));else morph(old,n);});
    while(current.childNodes.length>next.childNodes.length)current.lastChild.remove();
  }
  function region(id,html){const el=host?.querySelector('#'+id);if(!el)return;const next=document.createElement('div');next.innerHTML=html;const active=document.activeElement, key=host.contains(active)?active.dataset.key:null;const open=el.scrollTop;const holder=el.cloneNode(false);holder.append(...next.childNodes);morph(el,holder);el.scrollTop=open;if(key&&document.activeElement!==active){[...host.querySelectorAll('[data-key]')].find(x=>x.dataset.key===key)?.focus({preventScroll:true});}}
  function shell(){host.innerHTML=`<div class="gameday" data-focus="${s.focus}" data-density="${s.density}">
    <header class="gd-heading"><div><h1>Game Day</h1><p>Your matchup. Every game. The plays that matter.</p></div><div class="gd-mode" aria-label="Primary view"><button data-action="focus" data-value="matchup" data-key="view-matchup" aria-pressed="${s.focus==='matchup'}">My matchup</button><button data-action="focus" data-value="game" data-key="view-game" aria-pressed="${s.focus==='game'}">Game room</button></div></header>
    <section id="gd-score" aria-label="Weekly fantasy matchup"></section>
    <div class="gd-toolbar"><label class="gd-league-label" for="gd-league">Fantasy team / league<select id="gd-league" data-key="league">${leagues().map(l=>`<option value="${esc(l.id)}" ${String(l.id)===s.league?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><label for="gd-date">NFL game date<input id="gd-date" data-key="date" type="date" value="${s.date}" min="2000-01-01" max="2100-12-31"></label><button data-action="today" data-key="today">Today</button><div class="gd-update-actions"><button data-action="auto" data-key="auto" aria-pressed="${s.auto}">${s.auto?'Auto refresh on':'Auto refresh off'}</button><button data-action="refresh" data-key="refresh">Refresh now</button></div></div>
    <div id="gd-health" class="gd-health" role="status" aria-live="polite"></div>
    <section class="gd-slate" aria-labelledby="gd-slate-title"><div class="gd-section-head"><div><h2 id="gd-slate-title">${esc(dateLabel(s.date))}</h2><p id="gd-slate-meta" class="gd-muted">Checking today’s NFL games…</p></div><div class="gd-filter" aria-label="Filter NFL games"><button data-action="filter" data-value="all" data-key="filter-all" aria-pressed="true">All games</button><button data-action="filter" data-value="mine" data-key="filter-mine" aria-pressed="false">My players</button><button data-action="filter" data-value="matchup" data-key="filter-matchup" aria-pressed="false">My matchup</button></div></div><div id="gd-games" class="gd-game-list"></div></section>
    <div class="gd-columns"><section class="gd-panel gd-matchup-panel" aria-labelledby="gd-lineup-title"><header class="gd-panel-head"><h2 id="gd-lineup-title" tabindex="-1">The fantasy matchup</h2><label class="gd-density-label">Rows<select id="gd-density" data-key="density"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label></header><div class="gd-roster-tabs" aria-label="Roster selection"><button data-action="roster" data-value="starters" data-key="roster-starters" aria-pressed="true">Starters</button><button data-action="roster" data-value="bench" data-key="roster-bench" aria-pressed="false">Bench & reserves</button></div><div id="gd-lineups"></div><p class="gd-panel-foot">Select a player to follow their NFL game and see this league’s scoring context.</p></section>
    <section class="gd-panel gd-game-panel" aria-labelledby="gd-detail-title"><header class="gd-panel-head"><h2 id="gd-detail-title" tabindex="-1">Inside the game</h2><div class="gd-detail-actions"><span id="gd-detail-state" class="gd-muted"></span><button class="gd-back-lineup" data-action="back-lineup" data-key="back-lineup">Back to lineup</button></div></header><div id="gd-game-score" class="gd-game-score"></div><div class="gd-detail-tabs" aria-label="Selected game detail">${['field','leaders','plays','highlights'].map(k=>`<button data-action="detail" data-value="${k}" data-key="detail-${k}" aria-pressed="${k==='field'}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</div><div id="gd-game-detail" class="gd-game-detail"></div><div id="gd-player-context"></div><div id="gd-game-sources" class="gd-game-sources"></div></section></div>
    <details class="gd-provenance"><summary>Data sources and what the numbers mean</summary><div id="gd-sources"></div><p>Fantasy points are the league platform’s reported weekly totals. NFL scores and game statistics come from the game feed. Sources may update at different times; totals can change after scoring corrections.</p><p>The date picker changes the NFL slate. Your fantasy matchup follows the provider’s current week. Saved lessons and news keep their own research dates.</p></details><p class="gd-bottom-note">Times use your device’s time zone. Automatic updates run every 30 seconds while Game Day is visible. Use your fantasy platform for lineup changes.</p>
  </div>`;host.querySelector('#gd-density').value=s.density;host.querySelector('.gd-league-label').hidden=options.hideLeaguePicker===true;host.querySelector('#gd-date').min=dateBound(-370);host.querySelector('#gd-date').max=dateBound(370);host.addEventListener('click',click);host.addEventListener('change',change);host.addEventListener('error',imageError,true);}
  function renderHealth(){
    const stale=list(s.dashboard?.sources).some(x=>['stale','unavailable'].includes(x.status));
    const label=s.loading?'Checking the feeds…':s.error?(s.dashboard?'Update failed. Showing the last successful check.':'The live desk could not be loaded.'):stale?'Some sources need attention.':s.dashboard?'Feeds checked.':'Waiting for the first check.';
    region('gd-health',`<span class="gd-status-dot ${s.error||stale?'gd-status-warn':''}" aria-hidden="true"></span><b>${esc(label)}</b><span>${s.dashboard?esc(stamp(s.dashboard.generatedAt)):'Refresh to try again.'}</span><span class="gd-refresh-mode">${document.hidden?'Updates paused while this tab is hidden.':s.auto?'Updates on while this tab is visible.':'Automatic updates paused.'}</span>${s.error?`<p class="gd-health-error">${esc(s.error)}</p>`:''}${list(s.dashboard?.notices).map(n=>`<p class="gd-health-note">${esc(typeof n==='string'?n:n.message||n.text||'')}</p>`).join('')}`);
    const refresh=host?.querySelector('[data-action="refresh"]');if(refresh){refresh.disabled=s.loading;refresh.textContent=s.loading?'Refreshing…':'Refresh now';}
  }
  function counts(t){let live=0,done=0,remaining=0;for(const p of list(t?.starters)){const g=games().find(g=>String(g.id)===String(p.gameId));if(g?.state==='in')live++;else if(g?.state==='post')done++;else if(g?.state==='pre')remaining++;}const parts=[];if(live)parts.push(`${live} playing on this slate`);if(remaining)parts.push(`${remaining} yet to play on this slate`);if(done)parts.push(`${done} finished on this slate`);return parts.join(' · ')||'See player rows for game status';}
  function score(){const m=s.dashboard?.matchup,l=selectedLeague();if(!m?.own)return `<div class="gd-score-unavailable"><h2>Your weekly matchup</h2><p>${s.loading?'Checking your league’s current matchup…':'The current matchup is unavailable. NFL games remain available below.'}</p>${m?.reason?`<p class="gd-muted">${esc(m.reason)}</p>`:''}</div>`;const side=(t,own)=>`<div class="gd-score-side ${own?'':'gd-score-opponent'}"><div><span class="gd-score-label">${own?'Your team':'Opponent'}</span><h2>${esc(t?.name||(own?'Your team':'Opponent unavailable'))}</h2><p>${t?esc(counts(t)):'Opponent details are unavailable from the source.'}</p></div><div class="gd-total"><strong>${points(t?.points)}</strong><span>fantasy points</span></div></div>`;return `<div class="gd-matchup-banner"><div class="gd-banner-top"><span>${esc(l.name||'Fantasy matchup')}</span><span>${m.week||s.dashboard.week?`Week ${esc(m.week||s.dashboard.week)}`:'Current week'} · ${esc(l.platform||'Sleeper')}</span></div><div class="gd-head-to-head">${side(m.own,true)}<span class="gd-vs">vs</span>${side(m.opponent,false)}</div>${matchupMargin(m)}<div class="gd-banner-bottom">${esc(l.formatSummary||'League-scored weekly totals')}${!m.available?' · Partial matchup coverage':''}<span>Reported points · no estimated win odds</span></div>${matchupFreshness()}</div>`;}
  function matchupMargin(m){if(!finite(m.own?.points)||!finite(m.opponent?.points))return '';const gap=Math.round((m.own.points-m.opponent.points)*100)/100;const text=gap===0?'The matchup is tied':gap>0?`You lead by ${gap.toFixed(2)}`:`You trail by ${Math.abs(gap).toFixed(2)}`;return `<p class="gd-matchup-margin"><b>${esc(text)}</b><span>Based on reported points at this check</span></p>`;}
  function matchupFreshness(){const sources=list(s.dashboard?.sources).filter(x=>x.status==='snapshot'||/sleeper|fantasy|roster|matchup/i.test(x.provider||''));if(!sources.length)return '';return `<div class="gd-matchup-freshness">${sources.map(x=>`<p><b>${esc(x.provider)} ${x.status==='snapshot'?'snapshot':'checked'}</b> · ${esc(stamp(x.fetchedAt))}${x.status==='snapshot'?'<br>Fantasy scores are a saved account snapshot. NFL game updates below are separate.':''}${['stale','unavailable'].includes(x.status)?' · Source '+esc(x.status):''}</p>`).join('')}</div>`;}
  function gameCard(g){const own=connected(g,'own').length,opp=connected(g,'opponent').length;return `<button class="gd-game-card ${g.state==='in'?'gd-game-live':''}" data-action="game" data-value="${esc(g.id)}" data-key="game-${esc(g.id)}" aria-pressed="${String(g.id)===s.gameId}"><span class="gd-card-status">${g.state==='in'?'<i aria-hidden="true"></i>':''}${esc(status(g))}</span>${[g.away,g.home].map(t=>`<span class="gd-card-team">${photo(t?.logo,t?.abbr,'gd-club-logo')}<b>${esc(t?.abbr||t?.name||'?')}</b><strong>${finite(t?.score)?t.score:'—'}</strong></span>`).join('')}<span class="gd-game-connections">${own?`<span class="gd-your-badge">${own} yours</span>`:''}${opp?`<span class="gd-opp-badge">${opp} opponent</span>`:''}${!own&&!opp?'NFL game':''}</span></button>`;}
  function renderSlate(){const filtered=games().filter(g=>s.filter==='all'||connected(g,'own').length||s.filter==='matchup'&&connected(g,'opponent').length);region('gd-games',filtered.length?filtered.map(gameCard).join(''):`<div class="gd-empty"><h3>${s.loading&&!s.dashboard?'Loading the NFL slate…':games().length?'No games match this filter.':'No NFL games returned for this date.'}</h3><p>${games().length?'Choose All games to see the complete slate.':'Choose another date or refresh the feed. An unavailable feed is not proof that no games are scheduled.'}</p></div>`);host.querySelector('#gd-slate-title').textContent=dateLabel(s.date);host.querySelector('#gd-slate-meta').textContent=`${games().length} ${games().length===1?'game':'games'} returned · ${filtered.length} shown · select a game to follow it`;}
  function statLine(p){const detail=p.gameId&&String(s.detail?.id)===String(p.gameId)?list(s.detail?.players).find(x=>String(x.id)===String(p.espnId)):null,line=detail?.statLine||p.statLine;if(typeof line==='string')return line;if(Array.isArray(line))return line.map(x=>typeof x==='string'?x:[x.value,x.label].filter(Boolean).join(' ')).join(' · ');return '';}
  function playerRow(p,side,index){if(!p)return `<div class="gd-player-empty" data-key="empty-${side}-${index}"><span aria-hidden="true">—</span><span class="sr-only">No player in this row</span></div>`;const g=playerGame(p);const key=side+':'+p.id,role=[p.position,p.slot&&p.slot!==p.position?p.slot:null,p.team].filter(Boolean).join(' · '),label=`${p.name}, ${role}, ${finite(p.points)?p.points.toFixed(2)+' reported fantasy points':'fantasy points unavailable'}. ${g?status(g)+'. Open game and scoring context.':'No linked game on this slate. Open scoring context.'}`;return `<button class="gd-player" data-action="player" data-value="${esc(key)}" data-key="player-${esc(key)}" aria-pressed="${key===s.player}" aria-label="${esc(label)}" aria-controls="gd-game-score gd-player-context">${photo(p.photo,p.name)}<span class="gd-player-name">${esc(p.name)}<small>${esc(role)}${p.injuryStatus?` <span class="gd-injury">${esc(p.injuryStatus)}</span>`:''}</small></span><strong class="gd-player-points">${points(p.points)}<small>pts</small></strong><span class="gd-player-status ${g?.state==='in'?'gd-live-text':''}">${esc(g?status(g):'Not in this date’s NFL slate')}</span><span class="gd-player-line">${esc(statLine(p)||'No stat line supplied')}</span></button>`;}
  function lineups(){const t=teams(),rows=t.map(({data})=>s.roster==='starters'?list(data?.starters):[...list(data?.bench),...list(data?.injuredReserve),...list(data?.taxi)]),n=Math.max(...rows.map(x=>x.length));if(!n)return `<div class="gd-empty"><h3>${s.loading?'Checking lineups…':'No verified players available in this view.'}</h3><p>Refresh the source or choose another league. We’ll show a lineup only when the provider returns it.</p></div>`;return `<div class="gd-lineup-labels"><span>${esc(t[0].data?.name||'Your team')}</span><span>${esc(t[1].data?.name||'Opponent unavailable')}</span></div>${Array.from({length:n},(_,i)=>`<div class="gd-player-pair" data-key="row-${s.roster}-${i}">${playerRow(rows[0][i],'own',i)}${playerRow(rows[1][i],'opponent',i)}</div>`).join('')}`;}
  function gameScore(){const g=game();if(!g)return `<div class="gd-empty"><h3>Select an NFL game.</h3><p>Its field position, leaders, plays and available highlights will appear here.</p></div>`;return `<div class="gd-selected-teams">${[g.away,g.home].map(t=>`<div>${photo(t?.logo,t?.abbr,'gd-selected-logo')}<b>${esc(t?.abbr||t?.name||'?')}</b><strong>${finite(t?.score)?t.score:'—'}</strong></div>`).join('')}</div><p class="gd-selected-status">${esc(status(g))}</p><p class="gd-muted gd-game-name">${esc(g.name||g.shortName||'')}${link(g.sourceUrl,'Game source')}</p>`;}
  function fieldView(){const g=game(),d=s.detail?.id===s.gameId?s.detail:null,pos=d?.fieldPosition||g?.fieldPosition,down=g?.downDistance||d?.game?.downDistance;const y=pos?.yardsToEndzone,has=finite(y)&&y>=0&&y<=100;const offense=[g?.away,g?.home].find(t=>String(t?.id)===String(pos?.possessionTeamId||g?.possessionTeamId));const defense=[g?.away,g?.home].find(t=>t&&t!==offense);const x=has?10+(100-y)*.8:null,dist=pos?.distance??pos?.yardsToFirstDown;const gain=has&&finite(dist)?Math.max(10,Math.min(90,x+dist*.8)):null;const last=d?.lastPlay||g?.lastPlay;const text=typeof last==='string'?last:last?.text||'';return `<div class="gd-field-context"><h3>${esc(offense?offense.abbr+' possession':'Field position')}</h3><b>${esc(down||'Down and distance unavailable')}</b></div>${has&&offense?`<div class="gd-field" role="img" aria-label="${esc(`${offense.abbr} possession, ${y} yards from the opponent’s end zone. ${down||''} Offense moves left to right.`)}"><span class="gd-endzone">${esc(offense.abbr)}</span><span class="gd-endzone gd-endzone-far">${esc(defense?.abbr||'Goal')}</span><span class="gd-midfield">50</span><span class="gd-scrimmage" style="left:${x}%"></span>${gain!==null?`<span class="gd-gain" style="left:${gain}%"></span>`:''}<span class="gd-ball" style="left:${x}%" aria-hidden="true">→</span></div><div class="gd-field-legend"><span>Blue: line of scrimmage</span>${gain!==null?'<span>Gold: line to gain</span>':''}<span>Offense moves →</span></div><p class="gd-muted">${y===0?'At the opponent’s goal line':`${y} yards to the opponent’s end zone`}. Field orientation follows the offense.</p>`:`<div class="gd-field-empty"><b>${g?.state==='pre'?'Waiting for kickoff':g?.state==='post'?'Game complete':'Field position unavailable'}</b><span>${g?.state==='post'?'See leaders and plays for the game story.':'The field appears when the feed supplies verified possession and ball position.'}</span></div>`}${text?`<section class="gd-last-play"><span>Last play</span><p>${esc(text)}</p></section>`:''}`;}
  function leadersView(){const d=s.detail,rows=list(d?.leaders);if(!rows.length)return emptyDetail('No game leaders supplied yet.','Leaders appear when the game feed returns player statistics.');const cats=[...new Set(rows.map(r=>r.category))];return `<div class="gd-leaders">${cats.map(cat=>`<section><h3>${esc(cat)}</h3><div class="gd-leader-pair">${rows.filter(r=>r.category===cat).map(r=>`<div class="gd-leader">${photo(r.athlete?.photo,r.athlete?.name)}<div><b>${esc(r.athlete?.name||'Player unavailable')}</b><span>${esc(r.athlete?.team||[game()?.away,game()?.home].find(t=>String(t?.id)===String(r.teamId))?.abbr||'')}</span><strong>${esc(r.displayValue??'—')}</strong></div></div>`).join('')}</div></section>`).join('')}</div>`;}
  function playsView(){const plays=list(s.detail?.plays);if(!plays.length)return emptyDetail('No plays supplied yet.','Check again after kickoff, or open the source game page.');return `<ol class="gd-plays">${plays.map(p=>`<li class="${p.scoring?'gd-scoring-play':''}" data-key="play-${esc(p.id)}"><span class="gd-play-clock">${p.period?'Q'+esc(p.period):''}<b>${esc(p.clock||'')}</b>${p.scoring?'<em>Scoring play</em>':''}</span><div><p>${esc(p.text||'Play description unavailable')}</p>${finite(p.awayScore)&&finite(p.homeScore)?`<small>${esc(game()?.away?.abbr)} ${p.awayScore} · ${esc(game()?.home?.abbr)} ${p.homeScore}</small>`:''}</div></li>`).join('')}</ol><p class="gd-muted">Provider play order. NFL scoring plays do not by themselves establish a fantasy-points change.</p>`;}
  function highlightsView(){const clips=list(s.detail?.highlights).filter(h=>safeURL(h.url));return clips.length?`<div class="gd-highlights">${clips.map(h=>`<article data-key="clip-${esc(h.id)}">${safeURL(h.thumbnail)?`<a class="gd-highlight-image" href="${esc(safeURL(h.url))}" target="_blank" rel="noopener noreferrer"><img src="${esc(safeURL(h.thumbnail))}" alt="${esc(h.title||'Game highlight')}" loading="lazy" referrerpolicy="no-referrer"><span aria-hidden="true">▷</span></a>`:''}<h3>${link(h.url,h.title||'Watch game highlight')}</h3>${h.description?`<p>${esc(h.description)}</p>`:''}<p class="gd-muted">${h.publishedAt?esc(stamp(h.publishedAt))+' · ':''}Opens at the source · click to watch</p></article>`).join('')}</div>`:emptyDetail('No verified highlight links returned.','Clips appear here when the selected game’s source provides them. Nothing plays automatically.');}
  function emptyDetail(title,text){return `<div class="gd-empty"><h3>${esc(title)}</h3><p>${esc(text)}</p></div>`;}
  function details(){if(!game())return '';const stale=s.detail?.id!==s.gameId;if(s.gameLoading&&stale)return emptyDetail('Loading the game…','Checking the game feed for field position, leaders, plays and highlights.');if(s.gameError&&stale)return emptyDetail('The game detail feed is unavailable.',s.gameError+' Use Refresh now to try again.');let html=s.detailTab==='leaders'?leadersView():s.detailTab==='plays'?playsView():s.detailTab==='highlights'?highlightsView():fieldView();if(s.gameError)html=`<p class="gd-inline-warning">Update failed. Showing the last successful game check. ${esc(s.gameError)}</p>`+html;return html;}
  function playerContext(){const p=selectedPlayer();if(!p)return `<div class="gd-player-prompt"><b>Make the connection</b><p>Pick a player in the matchup to connect their NFL game with your league’s scoring.</p></div>`;const l=selectedLeague(),r=l.scoringSettings||leagues().find(x=>String(x.id)===s.league)?.scoringSettings||{},fields=p.position==='DEF'?[['sack','per sack'],['int','per interception'],['fum_rec','per fumble recovery'],['def_td','per defensive TD'],['safe','per safety']]:p.position==='K'?[['xpm','per extra point'],['xpmiss','per missed extra point'],['fgmiss','per missed field goal']]:p.position==='QB'?[['pass_yd','per passing yard'],['pass_td','per passing TD'],['pass_int','per interception'],['rush_yd','per rushing yard'],['rush_td','per rushing TD']]:[['rec','per reception'],['bonus_rec_te','extra per TE reception'],['rec_yd','per receiving yard'],['rec_td','per receiving TD'],['rush_yd','per rushing yard'],['rush_td','per rushing TD'],['fum_lost','per lost fumble']];const rates=fields.filter(([key])=>finite(r[key])&&(key!=='bonus_rec_te'||p.position==='TE'));return `<section class="gd-player-context"><div class="gd-context-head">${photo(p.photo,p.name)}<div><span>${s.player.startsWith('own:')?'Your player':'Opponent’s player'}</span><h3>${esc(p.name)}</h3><p>${esc([p.position,p.team].filter(Boolean).join(' · '))}</p></div><strong>${points(p.points)}<small>weekly pts</small></strong></div><p>${esc(statLine(p)||'The league provider has not supplied a detailed stat line for this player.')}</p>${!playerGame(p)?'<p class="gd-context-absent">This player has no verified game link in the selected date’s NFL slate. The game panel keeps your previous game selection.</p>':''}<details data-key="scoring-explanation"><summary>How this league scores ${esc(p.position==='DEF'?'a defense':p.position==='K'?'a kicker':p.name.split(' ')[0])}</summary>${rates.length?`<dl class="gd-rates">${rates.map(([k,label])=>`<div><dt>${esc(label)}</dt><dd>${r[k]>0?'+':''}${r[k]}</dd></div>`).join('')}</dl>`:'<p>Position scoring uses the league’s full rules, including any bonuses or thresholds. Open your league to see the complete settings.</p>'}<p class="gd-muted">These are scoring rates, not a reconstructed box score. The weekly point total above is reported by the league platform and may include other scoring categories or corrections.</p><button data-action="learn" data-key="learn-player">Explore this player in the guide</button></details></section>`;}
  function render(){if(!host)return;renderHealth();region('gd-score',score());renderSlate();region('gd-lineups',lineups());renderGame();region('gd-sources',sourceLine(s.dashboard?.sources));syncControls();}
  function renderGame(){if(!host)return;region('gd-game-score',gameScore());region('gd-game-detail',details());region('gd-player-context',playerContext());region('gd-game-sources',s.detail?.id===s.gameId?sourceLine(s.detail.sources)+list(s.detail.notices).map(n=>`<p class="gd-muted">${esc(typeof n==='string'?n:n.message||'')}</p>`).join(''):'');host.querySelector('#gd-detail-state').textContent=s.gameLoading?'Checking…':game()?.state==='in'?'In progress':game()?.state==='post'?'Final':'';}
  function syncControls(){const root=host?.querySelector('.gameday');if(!root)return;root.dataset.focus=s.focus;root.dataset.density=s.density;host.querySelectorAll('[data-action]').forEach(b=>{const a=b.dataset.action;if(['focus','filter','roster'].includes(a))b.setAttribute('aria-pressed',String(s[a]===b.dataset.value));if(a==='detail')b.setAttribute('aria-pressed',String(s.detailTab===b.dataset.value));if(a==='auto'){b.setAttribute('aria-pressed',String(s.auto));b.textContent=s.auto?'Auto refresh on':'Auto refresh off';}});}
  function schedule(){clearTimeout(timer);if(!host||!s.auto||document.hidden)return;timer=setTimeout(()=>refresh(),POLL_MS);}
  async function fetchJSON(url,signal){if(window.NFL_DELIVERY?.mode==='hosted'){if(signal.aborted)throw new DOMException('Request cancelled','AbortError');const feed=window.NFLBrowserFeed;if(!feed)throw new Error('The browser feed did not load. Reload NFL FantasyCast to try again.');const endpoint=new URL(url,location.href),query=endpoint.searchParams,force=query.get('refresh')==='1';const result=await(endpoint.pathname.endsWith('/dashboard')?feed.getDashboard(query.get('date'),query.get('league'),force):feed.getGame(query.get('id'),force));if(signal.aborted)throw new DOMException('Request cancelled','AbortError');return result;}const response=await fetch(url,{signal,cache:'no-store',headers:{Accept:'application/json'}});const type=response.headers.get('content-type')||'';if(!response.ok){let message=`Local feed returned HTTP ${response.status}.`;if(type.includes('json')){try{const body=await response.json();if(typeof body.error==='string')message=body.error;}catch{}}throw new Error(message);}if(!type.includes('json'))throw new Error('The local live-data server is not running. Reopen NFL FantasyCast with its launcher.');return response.json();}
  async function dashboard(force=false){dashboardRequest?.abort();const controller=new AbortController();dashboardRequest=controller;const token=++dashboardSeq;s.loading=true;s.error='';renderHealth();try{const d=await fetchJSON('/api/fantasycast/dashboard?'+new URLSearchParams({date:s.date,league:s.league,...(force?{refresh:'1'}:{})}),controller.signal);if(!host||token!==dashboardSeq)return;if(!d||!Array.isArray(d.games))throw new Error('The live desk returned an incomplete response.');s.dashboard=d;s.loading=false;s.error='';if(!games().some(g=>String(g.id)===s.gameId)){const candidate=games().find(g=>g.state==='in'&&connected(g,'own').length)||games().find(g=>connected(g,'own').length)||games().find(g=>g.state==='in')||games()[0];s.gameId=candidate?String(candidate.id):'';s.detail=null;}render();}catch(e){if(!host||token!==dashboardSeq||e.name==='AbortError')return;s.loading=false;s.error=e.message;render();}finally{if(host&&token===dashboardSeq)s.loading=false;}}
  async function loadGame(force=false){gameRequest?.abort();const token=++gameSeq;if(!host||!s.gameId){s.gameLoading=false;return;}const id=s.gameId,controller=new AbortController();gameRequest=controller;s.gameLoading=true;s.gameError='';renderGame();try{const d=await fetchJSON('/api/fantasycast/game?'+new URLSearchParams({id,...(force?{refresh:'1'}:{})}),controller.signal);if(!host||token!==gameSeq||id!==s.gameId)return;if(!d||String(d.id)!==id)throw new Error('The game feed returned a different event.');s.detail=d;s.gameLoading=false;s.gameError='';renderGame();}catch(e){if(!host||token!==gameSeq||e.name==='AbortError')return;s.gameLoading=false;s.gameError=e.message;renderGame();}}
  async function refresh(force=false){if(!host)return;const token=++refreshSeq;clearTimeout(timer);await dashboard(force);if(!host||token!==refreshSeq)return;await loadGame(force);if(host&&token===refreshSeq)schedule();}
  function openGameOnMobile(returnKey=''){if(!matchMedia('(max-width: 760px)').matches)return;s.returnKey=returnKey;s.focus='game';persist();syncControls();host.querySelector('#gd-detail-title')?.focus({preventScroll:true});host.querySelector('.gd-game-panel')?.scrollIntoView({block:'start',behavior:'auto'});}
  function backToLineup(){s.focus='matchup';persist();syncControls();const target=[...host.querySelectorAll('[data-key]')].find(x=>x.dataset.key===s.returnKey)||host.querySelector('#gd-lineup-title');target?.focus({preventScroll:true});target?.scrollIntoView({block:'center',behavior:'auto'});}
  function interaction(){document.dispatchEvent(new CustomEvent('nfl:gameday-interaction',{detail:{source:'gameday'}}));}
  function click(e){const b=e.target.closest('[data-action]');if(!b||!host.contains(b))return;interaction();const a=b.dataset.action,v=b.dataset.value;if(a==='refresh'){refresh(true);return;}if(a==='auto'){s.auto=!s.auto;persist();syncControls();renderHealth();if(s.auto)refresh();else{clearTimeout(timer);}return;}if(a==='today'){changeDate(localDate());return;}if(a==='back-lineup'){backToLineup();return;}if(a==='focus'){s.focus=v;persist();syncControls();return;}if(a==='filter'){s.filter=v;renderSlate();syncControls();return;}if(a==='roster'){s.roster=v;region('gd-lineups',lineups());syncControls();return;}if(a==='detail'){s.detailTab=v;region('gd-game-detail',details());syncControls();return;}if(a==='game'){s.gameId=v;s.detail=null;if(selectedPlayer()&&String(selectedPlayer().gameId)!==v)s.player='';region('gd-lineups',lineups());renderSlate();renderGame();loadGame();openGameOnMobile('');return;}if(a==='player'){s.player=v;const p=selectedPlayer();if(p){const g=playerGame(p);if(g&&String(g.id)!==s.gameId){s.gameId=String(g.id);s.detail=null;loadGame();}region('gd-lineups',lineups());renderSlate();renderGame();openGameOnMobile('player-'+v);}return;}if(a==='learn'){const p=selectedPlayer();if(p&&typeof options.onPlayerLearning==='function')options.onPlayerLearning(p);else location.hash='#news?'+new URLSearchParams({league:s.league,q:p?.name||''});}}
  function change(e){if(e.target.id==='gd-league'){setLeague(e.target.value);options.onLeagueChange?.(s.league);}if(e.target.id==='gd-date')changeDate(e.target.value);if(e.target.id==='gd-density'){s.density=e.target.value;persist();syncControls();}interaction();}
  function changeDate(date){const input=host.querySelector('#gd-date');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date+'T12:00:00'))||date<input.min||date>input.max){input.setCustomValidity(`Choose a date from ${input.min} through ${input.max}.`);input.reportValidity();return;}input.setCustomValidity('');if(s.date===date)return;s.date=date;input.value=date;s.dashboard=null;s.detail=null;s.gameId='';s.gameError='';invalidate();render();refresh();}
  function setLeague(id){if(!host||s.league===String(id))return;s.league=String(id);host.querySelector('#gd-league').value=s.league;s.dashboard=null;s.detail=null;s.gameId='';s.player='';s.error='';s.gameError='';invalidate();render();refresh();}
  function invalidate(){refreshSeq++;dashboardSeq++;gameSeq++;dashboardRequest?.abort();gameRequest?.abort();clearTimeout(timer);s.loading=false;s.gameLoading=false;}
  function visibility(){if(!host)return;if(document.hidden){invalidate();renderHealth();}else{renderHealth();if(s.auto)refresh();}}
  function imageError(e){if(e.target.tagName==='IMG')e.target.classList.add('gd-image-failed');}
  function unmount(){if(!host)return;invalidate();host.removeEventListener('click',click);host.removeEventListener('change',change);host.removeEventListener('error',imageError,true);document.removeEventListener('visibilitychange',visibility);host=null;options={};}
  function mount(container,config={}){unmount();host=container;options=config;const pref=saved();s={league:String(config.leagueId||leagues()[0]?.id||''),date:localDate(),focus:['matchup','game'].includes(pref.focus)?pref.focus:'matchup',density:pref.density==='compact'?'compact':'comfortable',auto:pref.auto!==false,filter:'all',roster:'starters',detailTab:'field',dashboard:null,detail:null,gameId:'',player:'',returnKey:'',loading:false,gameLoading:false,error:'',gameError:''};shell();render();document.addEventListener('visibilitychange',visibility);if(!document.hidden)refresh();}
  window.NFLGameDay={mount,unmount,setLeague};
})();
